### ISSUE TITLE
Moving from Testing to Deployment

### ISSUE THREAD

**Issue by claw2** [gaites/av-guidance#19]
Clarify the process and requirements (delegation or statutory) that allows an AV model to go from the testing regime to the deployment regime.

**Comment by gaites** [comment]
In #23, I described a modified pre-clearance regime which might offer a way to handle the switch from testing. It sets up an automatic clearance regime if following state procedures, otherwise it's subject to review.

If those changes are accepted, a quick line making a clarifying remark could further help.

**Comment by gaites** [comment]
Resolved under aeb67d600f89291c04e192426b7e8729c5404776

Testing is a voluntary status which can be changed at manufacturer's election.
