### ISSUE TITLE
Refine Rebuttable Presumption

### ISSUE THREAD

**Issue by gaites** [gaites/av-guidance#8]
The rebuttable presumption creates a good burden shifting strategy. We need to think through the different scenarios and create a more comprehensive mechanism for covering unanticipated scenarios.

**Comment by claw2** [comment]
We also need to clarify what counts as "interference" which would sever the liability shift, specify that the type of "interference" means the owner or user of the car has tampered with the software or hardware of the AV apparatus in such a way that it no longer performed as the manufacturer designed.  

We also need to change the "Prior to commencing suit" so that the procedural mechanism allows for the party who did NOT own/use the AV can also raise that issue after adequate discovery (just in case and for fairness).

**Comment by rcphilbr** [comment]
technical edits: 
"Party to the suit and assum[es] any liabilit[y]..."
"require the moving [ ] party to show..."

**Comment by gaites** [comment]
[Michigan Liabiliy](http://www.legislature.mi.gov/documents/2015-2016/billenrolled/Senate/htm/2016-SNB-0998.htm) This liability section leaves it substantially unclear what happens when there's a software defect. At the very least I'm concerned that it doesn't give clear guidance to the judiciary.

**Comment by gaites** [comment]
- For any criminal or civil claim which ocurrs with a vehicle operating at SAE level 3 as certified by the manufacturer or the Department of Licensing, any party to an action based on the incident may establish a rebuttable presumption that the autonomous function of the vehicle was the proximate cause of the claim. The presumption may be established by showing by a preponderance of the evidence the following items:
    1. The autonomous functionality of the vehicle was engaged at the time the claim arose; 
    2. Any of the owner, operator, or other responsible party reasonably maintained the vehicle's autonomous driving components in accordance with applicable state law and manufacturer guidelines. 
Once such showing has been made, the manufacturer, upfitter, or other party which affixed and made available autonomous driving funcitonality to the vehicle operator may be joined in the action.

**Comment by gaites** [comment]
Changes made under aeb67d600f89291c04e192426b7e8729c5404776
